[build]
command = "yarn build"
publish = "/public"
environment = { NODE_VERSION = "16", NODE_ENV = "production" }

[[redirects]]
from = "/"
to = "/zh-cn/"
status = 302
conditions = { Language = ["zh", "zh-cn", "zh-tw", "zh-hk"] }
force = true

[[redirects]]
from = "/"
to = "/en-us/"
status = 302
conditions = { Language = ["en", "en-us"] }
force = true

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Feature-Policy = "accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'none'; camera 'none'; display-capture 'none'; document-domain 'none'; encrypted-media 'none'; fullscreen 'self'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; picture-in-picture 'none'; speaker 'none'; sync-xhr 'none'; usb 'none'; vibrate 'none'; wake-lock 'none'; webauthn 'none'"
